name: flutter_ptp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_svg: ^2.0.5
  app_settings: ^4.2.0
  connectivity_plus: ^3.0.6
  wifi_iot: ^0.3.18
  network_info_plus: ^3.0.5
  location: ^4.4.0
  # android_intent_plus: ^3.1.9
  # device_info_plus: ^8.2.2
  # permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Bold.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-BoldItalic.ttf
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Italic.ttf
          style: italic
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic

flutter_launcher_icons:
  remove_alpha_ios: true
  android: "launcher_icon"
  ios: true 
  image_path: "assets/launcher_icons/foreground.png"
  adaptive_icon_background: "assets/launcher_icons/background.png"
  adaptive_icon_foreground: "assets/launcher_icons/foreground.png"
  windows:
    generate: true
    image_path: "assets/launcher_icons/original.png"
    icon_size: 150
  macos:
    generate: true
    image_path: "assets/launcher_icons/original.png"